project:
  type: website
  output-dir: docs

website:
  title: "Jordan Patten Hardy"

  navbar:
    background: primary
    left:
      - text: "About Me"
        href: About_Me.qmd
      - text: "Projects"
        href: Projects.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jordanpattenhardy
      - icon: mortarboard
        href: https://scholar.google.com/citations?hl=en&user=xCWh7MUAAAAJ

format:
  html:
    theme: lux
    toc: true
    include-after-body: footer.html