project:
  type: website
  output-dir: docs

website:
  title: "Jordan Patten Hardy"

  navbar:
    background: primary
    left:
      - text: "About Me"
        href: About_Me.qmd
      - text: "Resume"
        href: Resume.qmd
      - text: "Projects"
        href: Projects.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jordanpattenhardy

format:
  html:
    theme: lux
    toc: true